#!/bin/bash
for i in $@
do
	echo "Now searching for $i."
	targets=$(echo "$targets $(sudo apt-cache search $i | dmenu -i -l 30 | cut -d " " -f 1)")
done

echo $targets
sudo apt-get install -y $targets
